version: '0.0.{build}'

branches:
  only:
  - develop
#  - master

assembly_info:
  patch: false

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

build_script:
  - ps: ./build.ps1
  
artifacts:
 - path: 'output\*.zip'

cache:
  - '%USERPROFILE%\.nuget\packages'